#!/bin/bash
#SBATCH -J omp_mm
#SBATCH -o omp_mm.out
#SBATCH -e omp_mm.err
#SBATCH -t 0-00:30
#SBATCH -p test
#SBATCH -N 1
#SBATCH -c 8
#SBATCH --mem=4000

PRO=omp_mm
rm -rf ${PRO}.dat
touch ${PRO}.dat

# Load required software modules
module load gcc/10.2.0-fasrc01

# Run program with 1, 2, 4, and 8 OpenMP threads
for i in 1 2 4 8
do
    export OMP_NUM_THREADS=${i}
    srun -c ${i} ./${PRO}.x >> ${PRO}.dat
done

